title: Wdbasql
description: WDBASQL  means   Wilmix  NOSQL.(W*SQL) is  a  Securable  database  invented  by  wilmix  jemin  j  in  GDollar, C# ,and JAVA  .No  need  to  write  SQL Queries but  to  pass  parameters  in  WDBASQL  database for PLSQL f(x)s.  We can  also   write   WDBASql queries  like    SQL/Oracle  Queries.
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
